#!/bin/sh
# Starts aesdsocket

start() {
    echo "Starting aesdsocket"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
}

stop() {
    echo "Stopping aesdsocket"
    start-stop-daemon -K -n aesdsocket
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    *)
       echo "Usage: $0 {start|stop}"
esac

exit 0
